"""Read-only adapter and compact cache builder for the CNR POW_COD release.

POW_COD is distributed as one or two SQLite databases whose reflection arrays
are packed into text columns.  The source files are treated as immutable
external evidence.  This module creates a small normalized sidecar for fast
d-spacing queries and never writes to the supplied POW_COD database. The
sidecar keeps compressed per-phase reflection blobs and a d-spacing bitset
index rather than materializing one SQLite row for every reflection.
"""

from __future__ import annotations

from contextlib import closing

from dataclasses import dataclass
from datetime import datetime, timezone
from collections import OrderedDict
import hashlib
import json
import math
import os
from pathlib import Path
import sqlite3
import struct
from typing import Any, Iterable, Mapping
import zlib

import numpy as np

from phasentic.domain.formula import ELEMENT_INDEX, is_molecular_organic, parse_formula
from phasentic.domain.models import Peak, ReferenceLine, ReferencePhase
from phasentic.domain.radiation import Radiation, d_from_two_theta, get_radiation
from phasentic.references.equivalence import EquivalenceError, EquivalenceSidecar


POWCOD_RELEASE = "2205"
POWCOD_SOURCE_URL = "https://www.ba.ic.cnr.it/softwareic/qualx/download/powcod-2205/"
POWCOD_SCHEMA_VERSION = "powcod-cache-2"
POWCOD_ADAPTER_VERSION = "powcod-adapter-2026-09-22"
POWCOD_RETRIEVAL_POLICY_VERSION = "compactness-major-support-exact-backfill-v2"
POWCOD_BOUNDED_RETRIEVAL_COMPACTNESS_SHARE = 0.80
POWCOD_INDEX_KIND = "compressed-reflections-d-bin-bitset"
POWCOD_D_BIN_WIDTH_ANGSTROM = 0.05
POWCOD_MAX_INDEX_D_ANGSTROM = 100.0
POWCOD_HIGH_D_BIN = int(POWCOD_MAX_INDEX_D_ANGSTROM / POWCOD_D_BIN_WIDTH_ANGSTROM) + 1
POWCOD_DEFAULT_CANDIDATE_LIMIT = 256
POWCOD_DECODED_PHASE_CACHE_SIZE = 6000
POWCOD_MAX_LINES_PER_PHASE = 400
POWCOD_RETRIEVAL_MODES = ("bounded_coarse", "exhaustive_exact")
_REFLECTION_MAGIC = b"PCOL"
_REFLECTION_ENCODING_VERSION = 1
POWCOD_LICENSE = "CNR POW_COD distribution; consult the CNR academic/commercial license before redistribution"
POWCOD_ATTRIBUTION = "POW_COD generated by the QualX authors from Crystallography Open Database structure information"


def _bounded_retrieval_quotas(max_candidates: int) -> tuple[int, int]:
    """Return the compactness and major-support lanes for a bounded lookup."""

    compactness = math.floor(max_candidates * POWCOD_BOUNDED_RETRIEVAL_COMPACTNESS_SHARE)
    return compactness, max_candidates - compactness


class PowCodError(RuntimeError):
    """Named fail-closed error for an unavailable or incompatible POW_COD asset."""

    code = "POWCOD_ERROR"


@dataclass(frozen=True)
class PowCodCacheResult:
    source_path: Path
    cache_path: Path
    info_path: Path | None
    release: str
    source_sha256: str
    info_sha256: str | None
    cache_sha256: str
    phase_count: int
    line_count: int
    schema_version: str = POWCOD_SCHEMA_VERSION


def _quote(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _open_read_only(path: Path, *, check_integrity: bool = True) -> sqlite3.Connection:
    resolved = Path(path).expanduser().resolve()
    if not resolved.is_file():
        raise PowCodError(f"POWCOD_NOT_FOUND: {resolved}")
    try:
        connection = sqlite3.connect(f"{resolved.as_uri()}?mode=ro", uri=True)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA query_only=ON")
        if check_integrity:
            integrity = connection.execute("PRAGMA integrity_check").fetchone()
            if integrity is None or str(integrity[0]).casefold() != "ok":
                connection.close()
                raise PowCodError(f"POWCOD_INTEGRITY_FAILED: {resolved}")
        return connection
    except sqlite3.Error as exc:
        raise PowCodError(f"POWCOD_UNREADABLE: {resolved}") from exc


def _tables(connection: sqlite3.Connection) -> tuple[str, ...]:
    rows = connection.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return tuple(str(row[0]) for row in rows)


def _columns(connection: sqlite3.Connection, table: str) -> dict[str, str]:
    rows = connection.execute(f"PRAGMA table_info({_quote(table)})").fetchall()
    return {str(row[1]).casefold(): str(row[1]) for row in rows}


def _find_table(connection: sqlite3.Connection, preferred: str, required: set[str]) -> str:
    for table in _tables(connection):
        if table.casefold() == preferred.casefold():
            columns = _columns(connection, table)
            if required.issubset(columns):
                return table
    for table in _tables(connection):
        if required.issubset(_columns(connection, table)):
            return table
    raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: required POW_COD reflection columns are missing")


def _column(columns: Mapping[str, str], *names: str) -> str | None:
    for name in names:
        if name.casefold() in columns:
            return columns[name.casefold()]
    return None


def _info_path(source_path: Path, explicit: Path | None) -> Path | None:
    if explicit is not None:
        return explicit.expanduser().resolve()
    candidates = (
        source_path.with_name(source_path.name + ".info"),
        source_path.with_suffix(".info"),
    )
    return next((candidate for candidate in candidates if candidate.is_file()), None)


def _packed_values(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, bytes):
        value = value.decode("utf-8", errors="replace")
    text = str(value).strip().strip("[]()")
    if not text:
        return []
    return [part.strip() for part in text.replace(";", ",").split(",") if part.strip()]


def _float_values(value: Any) -> list[float]:
    values: list[float] = []
    for part in _packed_values(value):
        try:
            parsed = float(part)
        except (TypeError, ValueError):
            continue
        if math.isfinite(parsed):
            values.append(parsed)
    return values



def _text(row: sqlite3.Row | None, columns: Mapping[str, str], *names: str) -> str | None:
    if row is None:
        return None
    selected = _column(columns, *names)
    if selected is None:
        return None
    value = row[selected]
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _schema(
    source_path: Path,
    info_path: Path | None,
    *,
    check_integrity: bool = True,
) -> tuple[str, dict[str, str], str | None, dict[str, str]]:
    with closing(_open_read_only(source_path, check_integrity=check_integrity)) as connection:
        # POW_COD 2205 stores packed d spacings and intensities in the main
        # database and keeps h/k/l, multiplicity, and cell metadata in the
        # companion ``.sq.info`` database. Older/synthetic fixtures may keep
        # h/k/l in the main table, so those columns remain optional below.
        table = _find_table(connection, "id", {"id", "dvalue", "intensita"})
        columns = _columns(connection, table)
    info_table: str | None = None
    info_columns: dict[str, str] = {}
    if info_path is not None and info_path.is_file():
        with closing(_open_read_only(info_path, check_integrity=check_integrity)) as connection:
            try:
                info_table = _find_table(connection, "info", {"id"})
                info_columns = _columns(connection, info_table)
            except PowCodError:
                info_table = None
    return table, columns, info_table, info_columns


def _fetch_info_rows(
    connection: sqlite3.Connection | None,
    table: str | None,
    columns: Mapping[str, str],
    id_column: str | None,
    ids: Iterable[str],
) -> dict[str, sqlite3.Row]:
    """Fetch only metadata for one bounded source batch.

    The native POW_COD 2205 ``.sq.info`` file is roughly two gigabytes. Loading
    every row at startup defeats the purpose of the compact sidecar and can
    exhaust a normal workstation. The table has an id index, so bounded IN
    queries preserve deterministic input order while keeping memory bounded.
    """

    if connection is None or table is None or id_column is None:
        return {}
    unique = tuple(sorted(set(ids)))
    if not unique:
        return {}
    selected = [id_column]
    for name in (
        "formula",
        "chemical_formula",
        "formula_sum",
        "name",
        "title",
        "compound_name",
        "mineralname",
        "source_url",
        "cod_url",
        "url",
        "spacegroup",
        "space_group",
        "a",
        "b",
        "c",
        "alpha",
        "beta",
        "gamma",
        "h",
        "k",
        "l",
    ):
        value = _column(columns, name)
        if value is not None and value not in selected:
            selected.append(value)
    result: dict[str, sqlite3.Row] = {}
    for offset in range(0, len(unique), 900):
        chunk = unique[offset : offset + 900]
        placeholders = ",".join("?" for _ in chunk)
        query = (
            f"SELECT {', '.join(_quote(value) for value in selected)} "
            f"FROM {_quote(table)} WHERE {_quote(id_column)} IN ({placeholders})"
        )
        for row in connection.execute(query, chunk):
            result[str(row[id_column]).strip()] = row
    return result


def _row_value(row: Mapping[str, Any] | sqlite3.Row | None, column: str | None) -> Any:
    if row is None or column is None:
        return None
    try:
        return row[column]
    except (IndexError, KeyError):
        return None


def _float_field(
    primary_row: Mapping[str, Any] | sqlite3.Row | None,
    primary_columns: Mapping[str, str],
    fallback_row: Mapping[str, Any] | sqlite3.Row | None,
    fallback_columns: Mapping[str, str],
    name: str,
) -> float | None:
    for row, columns in ((primary_row, primary_columns), (fallback_row, fallback_columns)):
        value = _row_value(row, _column(columns, name))
        if value is None:
            continue
        try:
            parsed = float(value)
        except (TypeError, ValueError):
            continue
        if math.isfinite(parsed):
            return parsed
    return None


def _encode_reflections(reflections: Iterable[tuple[float, float, str | None]]) -> bytes:
    """Encode one phase's reflection evidence compactly and deterministically.

    POW_COD stores packed arrays per phase. Expanding those arrays into one
    SQLite row per reflection multiplies the 458k-entry release into hundreds
    of millions of rows. This binary representation keeps the arrays packed,
    quantizes d spacings to the source's six-decimal precision, and compresses
    the result without discarding hkl evidence.
    """

    rows = tuple(reflections)
    payload = bytearray(struct.pack("<4sBI", _REFLECTION_MAGIC, _REFLECTION_ENCODING_VERSION, len(rows)))
    for d_spacing, _intensity, _hkl in rows:
        quantized = int(round(float(d_spacing) * 1_000_000.0))
        if not 0 < quantized <= 0xFFFFFFFF:
            raise PowCodError("POWCOD_REFLECTION_ENCODING: d spacing is outside the encodable range")
        payload.extend(struct.pack("<I", quantized))
    for _d_spacing, intensity, _hkl in rows:
        payload.extend(struct.pack("<f", float(intensity)))
    for _d_spacing, _intensity, hkl in rows:
        encoded = (hkl or "").encode("utf-8")
        if len(encoded) > 0xFFFF:
            raise PowCodError("POWCOD_REFLECTION_ENCODING: hkl evidence is too long")
        payload.extend(struct.pack("<H", len(encoded)))
        payload.extend(encoded)
    return zlib.compress(bytes(payload), level=9)


def _decode_reflections(blob: bytes) -> tuple[tuple[float, float, str | None], ...]:
    """Decode and validate a compact reflection blob from the sidecar."""

    try:
        payload = zlib.decompress(bytes(blob))
        magic, version, count = struct.unpack_from("<4sBI", payload, 0)
    except (TypeError, struct.error, zlib.error) as exc:
        raise PowCodError("POWCOD_CACHE_CORRUPT: reflection blob cannot be decoded") from exc
    if magic != _REFLECTION_MAGIC or version != _REFLECTION_ENCODING_VERSION:
        raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: reflection encoding version")
    offset = struct.calcsize("<4sBI")
    d_end = offset + 4 * count
    intensity_end = d_end + 4 * count
    if intensity_end > len(payload):
        raise PowCodError("POWCOD_CACHE_CORRUPT: reflection arrays are truncated")
    d_values = struct.unpack_from(f"<{count}I", payload, offset) if count else ()
    intensities = struct.unpack_from(f"<{count}f", payload, d_end) if count else ()
    offset = intensity_end
    hkl_values: list[str | None] = []
    for _ in range(count):
        if offset + 2 > len(payload):
            raise PowCodError("POWCOD_CACHE_CORRUPT: hkl evidence is truncated")
        size = struct.unpack_from("<H", payload, offset)[0]
        offset += 2
        if offset + size > len(payload):
            raise PowCodError("POWCOD_CACHE_CORRUPT: hkl evidence exceeds blob")
        text = payload[offset : offset + size].decode("utf-8") if size else ""
        offset += size
        hkl_values.append(text or None)
    return tuple((value / 1_000_000.0, float(intensity), hkl) for value, intensity, hkl in zip(d_values, intensities, hkl_values))


def _decode_reflection_arrays(blob: bytes) -> tuple[np.ndarray, np.ndarray, list[str | None] | None]:
    """Decode d-spacings and intensities as arrays; hkl text only for small blobs."""

    try:
        payload = zlib.decompress(bytes(blob))
        magic, version, count = struct.unpack_from("<4sBI", payload, 0)
    except (TypeError, struct.error, zlib.error) as exc:
        raise PowCodError("POWCOD_CACHE_CORRUPT: reflection blob cannot be decoded") from exc
    if magic != _REFLECTION_MAGIC or version != _REFLECTION_ENCODING_VERSION:
        raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: reflection encoding version")
    offset = struct.calcsize("<4sBI")
    d_end = offset + 4 * count
    intensity_end = d_end + 4 * count
    if intensity_end > len(payload):
        raise PowCodError("POWCOD_CACHE_CORRUPT: reflection arrays are truncated")
    d_values = np.frombuffer(payload, dtype="<u4", count=count, offset=offset).astype(np.float64) / 1_000_000.0
    intensities = np.frombuffer(payload, dtype="<f4", count=count, offset=d_end).astype(np.float64)
    hkl_values: list[str | None] | None = None
    if count <= POWCOD_MAX_LINES_PER_PHASE:
        hkl_values = [hkl for _d, _i, hkl in _decode_reflections(blob)]
    return d_values, intensities, hkl_values


def _decode_d_spacings(blob: bytes) -> np.ndarray:
    """Decode only d spacings for exhaustive position-recall scans.

    Exact candidate qualification does not need intensities or hkl strings.
    Avoiding those allocations keeps the full-library pass bounded in memory
    and substantially reduces Python work while preserving the same encoded
    source values used by ``_decode_reflections``.
    """

    try:
        payload = zlib.decompress(bytes(blob))
        magic, version, count = struct.unpack_from("<4sBI", payload, 0)
    except (TypeError, struct.error, zlib.error) as exc:
        raise PowCodError("POWCOD_CACHE_CORRUPT: reflection blob cannot be decoded") from exc
    if magic != _REFLECTION_MAGIC or version != _REFLECTION_ENCODING_VERSION:
        raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: reflection encoding version")
    offset = struct.calcsize("<4sBI")
    d_end = offset + 4 * count
    if d_end > len(payload):
        raise PowCodError("POWCOD_CACHE_CORRUPT: d-spacing array is truncated")
    encoded = np.frombuffer(payload, dtype="<u4", count=count, offset=offset)
    return encoded.astype(np.float64, copy=False) / 1_000_000.0


def _cache_hash(connection: sqlite3.Connection) -> str:
    digest = hashlib.sha256()
    for row in connection.execute(
        "SELECT phase_no, reference_id, cod_id, formula, name, space_group, source_url, "
        "a, b, c, alpha, beta, gamma, d_min, d_max, reflection_count, reflection_blob "
        "FROM phases ORDER BY phase_no"
    ):
        digest.update(json.dumps(tuple(row[:-1]), separators=(",", ":"), ensure_ascii=False).encode())
        digest.update(b"\n")
        digest.update(bytes(row[-1]))
        digest.update(b"\n")
    for row in connection.execute("SELECT bin, phase_bits FROM d_bin_index ORDER BY bin"):
        digest.update(struct.pack("<I", int(row[0])))
        digest.update(bytes(row[1]))
    return digest.hexdigest()


def _canonical_source_url(cod_id: str, supplied: str | None) -> str:
    return supplied or f"https://www.crystallography.net/cod/{cod_id}.html"


def build_powcod_cache(
    source_path: Path | str,
    cache_path: Path | str,
    *,
    info_path: Path | str | None = None,
    release: str = POWCOD_RELEASE,
) -> PowCodCacheResult:
    """Normalize a POW_COD release into a deterministic query sidecar."""

    source = Path(source_path).expanduser().resolve()
    if not source.is_file():
        raise PowCodError(f"POWCOD_NOT_FOUND: {source}")
    info = _info_path(source, Path(info_path) if info_path is not None else None)
    if info is not None and not info.is_file():
        raise PowCodError(f"POWCOD_INFO_NOT_FOUND: {info}")
    # Preparation reads both databases read-only and defers the full SQLite
    # integrity scan to ``powcod verify``. This keeps a multi-gigabyte build
    # from scanning every page twice while still providing an explicit
    # exhaustive verification command before runtime selection.
    table, columns, info_table, info_columns = _schema(source, info, check_integrity=False)
    id_column = _column(columns, "id")
    h_column = _column(columns, "h")
    k_column = _column(columns, "k")
    l_column = _column(columns, "l")
    d_column = _column(columns, "dvalue")
    intensity_column = _column(columns, "intensita")
    assert id_column and d_column and intensity_column
    space_group_column = _column(columns, "spacegroup", "spacegroup_x", "space_group")
    cell_columns = {name: _column(columns, name) for name in ("a", "b", "c", "alpha", "beta", "gamma")}
    source_formula_column = _column(columns, "formula", "chemical_formula", "formula_sum")
    source_name_column = _column(columns, "name", "title", "compound_name", "mineralname")
    source_url_column = _column(columns, "source_url", "cod_url", "url")
    info_id_column = _column(info_columns, "id") if info_table is not None else None
    info_h_column = _column(info_columns, "h")
    info_k_column = _column(info_columns, "k")
    info_l_column = _column(info_columns, "l")
    source_sha = _sha256(source)
    info_sha = _sha256(info) if info is not None else None
    output = Path(cache_path).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.building")
    temporary.unlink(missing_ok=True)
    source_stat = source.stat()
    info_stat = info.stat() if info is not None else None
    try:
        with closing(_open_read_only(source, check_integrity=False)) as source_connection:
            info_connection = (
                _open_read_only(info, check_integrity=False)
                if info is not None and info_table is not None
                else None
            )
            try:
                with closing(sqlite3.connect(temporary)) as cache:
                    cache.executescript(
                    """
                    PRAGMA journal_mode=DELETE;
                    CREATE TABLE metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
                    CREATE TABLE phases (
                        phase_no INTEGER PRIMARY KEY,
                        reference_id TEXT NOT NULL UNIQUE,
                        cod_id TEXT NOT NULL,
                        formula TEXT NOT NULL,
                        name TEXT NOT NULL,
                        space_group TEXT NOT NULL,
                        source_url TEXT NOT NULL,
                        a REAL, b REAL, c REAL, alpha REAL, beta REAL, gamma REAL,
                        d_min REAL,
                        d_max REAL,
                        reflection_count INTEGER NOT NULL,
                        reflection_blob BLOB NOT NULL
                    );
                    CREATE UNIQUE INDEX phases_reference_idx ON phases(reference_id);
                    CREATE TABLE d_bin_index (
                        bin INTEGER PRIMARY KEY,
                        phase_bits BLOB NOT NULL
                    );
                    CREATE TABLE quality_flags (
                        reference_id TEXT NOT NULL,
                        code TEXT NOT NULL,
                        message TEXT NOT NULL
                    );
                    """
                    )
                    metadata = {
                    "schema_version": POWCOD_SCHEMA_VERSION,
                    "adapter_version": POWCOD_ADAPTER_VERSION,
                    "index_kind": POWCOD_INDEX_KIND,
                    "d_bin_width_angstrom": str(POWCOD_D_BIN_WIDTH_ANGSTROM),
                    "max_index_d_angstrom": str(POWCOD_MAX_INDEX_D_ANGSTROM),
                    "reflection_encoding": f"{_REFLECTION_MAGIC.decode('ascii')}-{_REFLECTION_ENCODING_VERSION}",
                    "release": str(release),
                    "source_path_name": source.name,
                    "source_sha256": source_sha,
                    "source_size": str(source_stat.st_size),
                    "source_mtime_ns": str(source_stat.st_mtime_ns),
                    "info_path_name": info.name if info is not None else "",
                    "info_sha256": info_sha or "",
                    "info_size": str(info_stat.st_size) if info_stat is not None else "",
                    "info_mtime_ns": str(info_stat.st_mtime_ns) if info_stat is not None else "",
                    "source_url": POWCOD_SOURCE_URL,
                    "license": POWCOD_LICENSE,
                    "attribution": POWCOD_ATTRIBUTION,
                    "intensity_model": "POW_COD calculated relative intensities; native configuration must be verified per release",
                    "build_status": "building",
                }
                    cache.executemany("INSERT INTO metadata(key, value) VALUES (?, ?)", metadata.items())
                    phase_count = 0
                    line_count = 0
                    estimated_phase_rows = int(source_connection.execute(f"SELECT COUNT(*) FROM {_quote(table)}").fetchone()[0])
                    bitset_length = max(1, (estimated_phase_rows + 7) // 8)
                    d_bin_bits: dict[int, bytearray] = {}
                    phase_rows: list[tuple[Any, ...]] = []
                    flag_rows: list[tuple[Any, ...]] = []
                    select_columns: list[str] = [id_column]
                    for candidate in (
                        space_group_column,
                        source_formula_column,
                        source_name_column,
                        source_url_column,
                        *cell_columns.values(),
                        h_column,
                        k_column,
                        l_column,
                        d_column,
                        intensity_column,
                    ):
                        if candidate and candidate not in select_columns:
                            select_columns.append(candidate)
                    source_columns = {key.casefold(): key for key in select_columns}
                    source_cursor = source_connection.execute(
                        f"SELECT {', '.join(_quote(value) for value in select_columns)} "
                        f"FROM {_quote(table)} ORDER BY {_quote(id_column)}"
                    )
                    while True:
                        source_batch = source_cursor.fetchmany(1000)
                        if not source_batch:
                            break
                        source_ids = (str(row[id_column]).strip() for row in source_batch if row[id_column] is not None)
                        info_rows = _fetch_info_rows(
                            info_connection,
                            info_table,
                            info_columns,
                            info_id_column,
                            source_ids,
                        )
                        for row in source_batch:
                            raw_id = row[id_column]
                            cod_id = str(raw_id).strip() if raw_id is not None else ""
                            if not cod_id:
                                continue
                            info_row = info_rows.get(cod_id)
                            formula = (
                                _text(row, source_columns, "formula", "chemical_formula", "formula_sum")
                                or _text(info_row, info_columns, "formula", "chemical_formula", "formula_sum")
                                or "Unknown"
                            )
                            name = (
                                _text(row, source_columns, "name", "title", "compound_name", "mineralname")
                                or _text(info_row, info_columns, "name", "title", "compound_name", "mineralname")
                                or f"COD {cod_id}"
                            )
                            supplied_url = (
                                _text(row, source_columns, "source_url", "cod_url", "url")
                                or _text(info_row, info_columns, "source_url", "cod_url", "url")
                            )
                            space_group = (
                                _text(row, source_columns, "spacegroup", "spacegroup_x", "space_group")
                                or _text(info_row, info_columns, "spacegroup", "space_group")
                                or "Unknown"
                            )
                            reference_id = f"powcod:{cod_id}"
                            d_values = _float_values(_row_value(row, d_column))
                            intensities = _float_values(_row_value(row, intensity_column))
                            h_values = _packed_values(_row_value(row, h_column)) or _packed_values(_row_value(info_row, info_h_column))
                            k_values = _packed_values(_row_value(row, k_column)) or _packed_values(_row_value(info_row, info_k_column))
                            l_values = _packed_values(_row_value(row, l_column)) or _packed_values(_row_value(info_row, info_l_column))
                            usable = min(len(d_values), len(intensities))
                            reflections: list[tuple[float, float, str | None]] = []
                            for index in range(usable):
                                d_value = d_values[index]
                                intensity = intensities[index]
                                if not math.isfinite(d_value) or d_value <= 0 or not math.isfinite(intensity) or intensity < 0:
                                    continue
                                hkl = None
                                if index < len(h_values) and index < len(k_values) and index < len(l_values):
                                    components = (h_values[index], k_values[index], l_values[index])
                                    hkl = (
                                        "".join(components)
                                        if all(len(component) == 1 and component.isdigit() for component in components)
                                        else " ".join(components)
                                    )
                                reflections.append((d_value, intensity, hkl))
                            phase_no = phase_count
                            phase_count += 1
                            d_min = min((reflection[0] for reflection in reflections), default=None)
                            d_max = max((reflection[0] for reflection in reflections), default=None)
                            phase_rows.append(
                                (
                                    phase_no,
                                    reference_id,
                                    cod_id,
                                    formula,
                                    name,
                                    space_group,
                                    _canonical_source_url(cod_id, supplied_url),
                                    *(
                                        _float_field(row, source_columns, info_row, info_columns, field)
                                        for field in cell_columns
                                    ),
                                    d_min,
                                    d_max,
                                    len(reflections),
                                    _encode_reflections(reflections),
                                )
                            )
                            line_count += len(reflections)
                            for d_value, _intensity, _hkl in reflections:
                                bin_number = min(
                                    int(math.floor(d_value / POWCOD_D_BIN_WIDTH_ANGSTROM)),
                                    POWCOD_HIGH_D_BIN,
                                )
                                bits = d_bin_bits.setdefault(bin_number, bytearray(bitset_length))
                                bits[phase_no // 8] |= 1 << (phase_no % 8)
                            if not reflections:
                                flag_rows.append((reference_id, "no_valid_reflections", "No usable d-spacing/intensity pair was present in POW_COD row"))
                            if len(phase_rows) >= 1000:
                                cache.executemany("INSERT INTO phases VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", phase_rows)
                                cache.executemany("INSERT INTO quality_flags VALUES (?, ?, ?)", flag_rows)
                                phase_rows.clear()
                                flag_rows.clear()
                    if phase_rows:
                        cache.executemany("INSERT INTO phases VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", phase_rows)
                        cache.executemany("INSERT INTO quality_flags VALUES (?, ?, ?)", flag_rows)
                    actual_bitset_length = max(1, (phase_count + 7) // 8)
                    cache.executemany(
                        "INSERT INTO d_bin_index(bin, phase_bits) VALUES (?, ?)",
                        ((bin_number, bytes(bits[:actual_bitset_length])) for bin_number, bits in sorted(d_bin_bits.items())),
                    )
                    cache_hash = _cache_hash(cache)
                    cache.executemany(
                        "INSERT INTO metadata(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
                        (("phase_count", str(phase_count)), ("line_count", str(line_count)), ("cache_sha256", cache_hash), ("build_status", "complete")),
                    )
                    cache.commit()
            finally:
                if info_connection is not None:
                    info_connection.close()
        os.replace(temporary, output)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
    return PowCodCacheResult(source, output, info, str(release), source_sha, info_sha, cache_hash, phase_count, line_count)


def write_powcod_manifest(path: Path | str, result: PowCodCacheResult) -> None:
    payload = {
        "schema_version": "powcod-manifest-1",
        "cache_schema_version": result.schema_version,
        "cache_index_kind": POWCOD_INDEX_KIND,
        "cache_d_bin_width_angstrom": POWCOD_D_BIN_WIDTH_ANGSTROM,
        "cache_max_index_d_angstrom": POWCOD_MAX_INDEX_D_ANGSTROM,
        "cache_reflection_encoding": f"{_REFLECTION_MAGIC.decode('ascii')}-{_REFLECTION_ENCODING_VERSION}",
        "release": result.release,
        "source_url": POWCOD_SOURCE_URL,
        "source_path_name": result.source_path.name,
        "source_sha256": result.source_sha256,
        "source_size": result.source_path.stat().st_size,
        "info_path_name": result.info_path.name if result.info_path else None,
        "info_sha256": result.info_sha256,
        "cache_path_name": result.cache_path.name,
        "cache_sha256": result.cache_sha256,
        "phase_count": result.phase_count,
        "line_count": result.line_count,
        "license": POWCOD_LICENSE,
        "attribution": POWCOD_ATTRIBUTION,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    destination = Path(path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.building")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(temporary, destination)


def verify_powcod_source(
    source_path: Path | str,
    *,
    info_path: Path | str | None = None,
) -> dict[str, object]:
    """Exhaustively validate a POW_COD source pair before runtime use.

    Preparation intentionally avoids repeating this multi-gigabyte scan. The
    explicit CLI verification command performs it once, records the source
    hashes, and leaves the read-only source databases untouched.
    """

    source = Path(source_path).expanduser().resolve()
    if not source.is_file():
        raise PowCodError(f"POWCOD_NOT_FOUND: {source}")
    info = _info_path(source, Path(info_path) if info_path is not None else None)
    if info is not None and not info.is_file():
        raise PowCodError(f"POWCOD_INFO_NOT_FOUND: {info}")
    table, _columns_map, info_table, _info_columns_map = _schema(source, info, check_integrity=True)
    with closing(_open_read_only(source, check_integrity=False)) as connection:
        source_rows = int(connection.execute(f"SELECT COUNT(*) FROM {_quote(table)}").fetchone()[0])
    info_rows = None
    if info is not None and info_table is not None:
        with closing(_open_read_only(info, check_integrity=False)) as connection:
            info_rows = int(connection.execute(f"SELECT COUNT(*) FROM {_quote(info_table)}").fetchone()[0])
    return {
        "source_path": str(source),
        "source_sha256": _sha256(source),
        "source_table": table,
        "source_rows": source_rows,
        "info_path": str(info) if info is not None else None,
        "info_sha256": _sha256(info) if info is not None else None,
        "info_table": info_table,
        "info_rows": info_rows,
        "status": "complete",
    }


class PowCodReferenceStore:
    """Read-only POW_COD sidecar-backed store with d-spacing candidate lookup."""

    def __init__(
        self,
        source_path: Path | str,
        *,
        cache_path: Path | str | None = None,
        info_path: Path | str | None = None,
        equivalence_path: Path | str | None = None,
    ) -> None:
        self.source_path = Path(source_path).expanduser().resolve()
        self.cache_path = Path(cache_path).expanduser().resolve() if cache_path is not None else self.source_path.with_name(self.source_path.name + ".xrd.sqlite")
        self.info_path = _info_path(self.source_path, Path(info_path) if info_path is not None else None)
        self.equivalence_path = Path(equivalence_path).expanduser().resolve() if equivalence_path is not None else None
        self._equivalence: EquivalenceSidecar | None = None
        if not self.source_path.is_file():
            raise PowCodError(f"POWCOD_NOT_FOUND: {self.source_path}")
        if not self.cache_path.is_file():
            raise PowCodError(f"POWCOD_CACHE_NOT_FOUND: run phasentic powcod prepare for {self.source_path.name}")
        # ``powcod verify`` is the explicit integrity gate.  Re-running a
        # multi-gigabyte SQLite integrity scan for every measured case would
        # make a 100-case campaign needlessly take hours before any matching
        # work begins.  Runtime still authenticates the immutable cache via
        # schema, build status, source stat identity, and the recorded cache
        # hash; operators can (and release checks do) run the exhaustive
        # verifier once before selecting the cache.
        self._connection = _open_read_only(self.cache_path, check_integrity=False)
        self._last_query_stats: dict[str, object] = {
            "candidate_limit": POWCOD_DEFAULT_CANDIDATE_LIMIT,
            "candidate_count": 0,
            "returned_count": 0,
            "truncated": False,
            "retrieval_mode": "bounded_coarse",
            "scanned_phase_count": 0,
            "selection": "compactness_major_support_union_coarse_d_bin_hits",
            "retrieval_policy_version": POWCOD_RETRIEVAL_POLICY_VERSION,
        }
        self._reflection_counts: np.ndarray | None = None
        # Decoded phases are pure functions of (phase_no, wavelength); residual
        # re-queries decode the same rows repeatedly, so keep a bounded LRU.
        self._decoded_phase_cache: OrderedDict[tuple[int, float], tuple[np.ndarray, ReferencePhase | None]] = OrderedDict()
        self._element_masks: np.ndarray | None = None
        try:
            metadata = self._metadata()
            if metadata.get("schema_version") != POWCOD_SCHEMA_VERSION:
                raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: cache schema version")
            if metadata.get("index_kind") != POWCOD_INDEX_KIND:
                raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: cache index kind")
            if metadata.get("reflection_encoding") != f"{_REFLECTION_MAGIC.decode('ascii')}-{_REFLECTION_ENCODING_VERSION}":
                raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: reflection encoding")
            if metadata.get("build_status") != "complete":
                raise PowCodError("POWCOD_CACHE_INCOMPLETE")
            try:
                self._phase_count = int(metadata["phase_count"])
                self._d_bin_width = float(metadata["d_bin_width_angstrom"])
                self._max_index_d = float(metadata["max_index_d_angstrom"])
            except (KeyError, TypeError, ValueError) as exc:
                raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: cache index metadata") from exc
            if (
                not math.isfinite(self._d_bin_width)
                or self._d_bin_width <= 0
                or not math.isfinite(self._max_index_d)
                or self._max_index_d <= 0
                or self._phase_count < 0
                or not math.isclose(self._d_bin_width, POWCOD_D_BIN_WIDTH_ANGSTROM, rel_tol=0.0, abs_tol=1e-12)
                or not math.isclose(self._max_index_d, POWCOD_MAX_INDEX_D_ANGSTROM, rel_tol=0.0, abs_tol=1e-9)
            ):
                raise PowCodError("POWCOD_SCHEMA_UNSUPPORTED: cache index metadata values")
            stat = self.source_path.stat()
            if str(stat.st_size) != metadata.get("source_size") or str(stat.st_mtime_ns) != metadata.get("source_mtime_ns"):
                raise PowCodError("POWCOD_SOURCE_CHANGED: rebuild the POW_COD cache")
            expected_info_size = metadata.get("info_size", "")
            expected_info_mtime = metadata.get("info_mtime_ns", "")
            if expected_info_size or expected_info_mtime:
                if self.info_path is None or not self.info_path.is_file():
                    raise PowCodError("POWCOD_INFO_CHANGED: rebuild the POW_COD cache")
                info_stat = self.info_path.stat()
                if str(info_stat.st_size) != expected_info_size or str(info_stat.st_mtime_ns) != expected_info_mtime:
                    raise PowCodError("POWCOD_INFO_CHANGED: rebuild the POW_COD cache")
            if self.equivalence_path is not None:
                try:
                    self._equivalence = EquivalenceSidecar.open(
                        self.equivalence_path,
                        expected_source_sha256=metadata.get("source_sha256"),
                        expected_cache_sha256=metadata.get("cache_sha256"),
                    )
                except EquivalenceError as exc:
                    raise PowCodError(f"POWCOD_EQUIVALENCE_INVALID: {exc}") from exc
        except Exception:
            self.close()
            raise

    def _metadata(self) -> dict[str, str]:
        return {str(row["key"]): str(row["value"]) for row in self._connection.execute("SELECT key, value FROM metadata")}

    def metadata(self) -> dict[str, str]:
        return dict(self._metadata())

    def provenance(self) -> dict[str, object]:
        metadata = self._metadata()
        return {
            "reference_source": "pow_cod",
            "reference_database": "POW_COD",
            "powcod_release": metadata.get("release"),
            "powcod_source_url": metadata.get("source_url", POWCOD_SOURCE_URL),
            "powcod_database_sha256": metadata.get("source_sha256"),
            "powcod_cache_sha256": metadata.get("cache_sha256"),
            "powcod_schema_version": metadata.get("schema_version"),
            "powcod_adapter_version": metadata.get("adapter_version"),
            "powcod_index_kind": metadata.get("index_kind"),
            "powcod_d_bin_width_angstrom": metadata.get("d_bin_width_angstrom"),
            "powcod_max_index_d_angstrom": metadata.get("max_index_d_angstrom"),
            "powcod_reflection_encoding": metadata.get("reflection_encoding"),
            "powcod_retrieval_policy_version": POWCOD_RETRIEVAL_POLICY_VERSION,
            "powcod_runtime_integrity_gate": "metadata_and_hash_bound; exhaustive_integrity_check_via_powcod_verify",
            "powcod_intensity_model": metadata.get("intensity_model"),
            "powcod_license": metadata.get("license"),
            "powcod_attribution": metadata.get("attribution"),
            "powcod_equivalence_sidecar": str(self.equivalence_path) if self.equivalence_path else None,
            "powcod_equivalence_content_sha256": self._equivalence.metadata().get("content_sha256") if self._equivalence else None,
            "powcod_equivalence_method_version": self._equivalence.metadata().get("method_version") if self._equivalence else None,
        }

    def intensity_policy(self, radiation: Radiation | str) -> dict[str, object]:
        selected = get_radiation(radiation)
        if selected.key == "cu_ka":
            return {
                "mode": "native_calculated",
                "intensity_scoring": True,
                "intensity_comparison": "supported",
                "warning": None,
                "radiation": selected.key,
            }
        return {
            "mode": "position_only",
            "intensity_scoring": False,
            "intensity_comparison": "unsupported",
            "warning": "POWCOD_INTENSITY_UNSUPPORTED",
            "radiation": selected.key,
        }

    def query_stats(self) -> dict[str, object]:
        """Return immutable metadata for the most recent bounded candidate query."""

        return dict(self._last_query_stats)

    def _reflection_count_array(self) -> np.ndarray:
        """Per-phase reflection counts (floored at 1), shape (phase_count,) float64.

        Reading the ``reflection_count`` column scans the whole phases table,
        which on a multi-gigabyte cache costs tens of seconds per process. The
        vector is therefore stored beside the cache, bound to the cache hash,
        exactly like the element-mask sidecar.
        """

        if self._reflection_counts is not None:
            return self._reflection_counts
        cache_sha = self._metadata().get("cache_sha256", "unknown")
        sidecar = self.cache_path.with_name(f"{self.cache_path.name}.refcounts1-{cache_sha[:16]}.npy")
        if sidecar.is_file():
            try:
                counts = np.load(sidecar, allow_pickle=False)
                if counts.shape == (self._phase_count,) and counts.dtype == np.float64:
                    self._reflection_counts = counts
                    return counts
            except (OSError, ValueError):
                pass
        counts = np.zeros(self._phase_count, dtype=np.float64)
        for phase_no, reflection_count in self._connection.execute(
            "SELECT phase_no, reflection_count FROM phases ORDER BY phase_no"
        ):
            index = int(phase_no)
            if 0 <= index < self._phase_count:
                counts[index] = max(float(reflection_count or 0.0), 1.0)
        self._reflection_counts = counts
        try:
            temporary = sidecar.with_suffix(".tmp.npy")
            np.save(temporary, counts, allow_pickle=False)
            os.replace(temporary, sidecar)
        except OSError:
            pass
        return counts

    def _element_mask_array(self) -> np.ndarray:
        """Per-phase element bit masks and an organic flag, shape (phase_count, 3) uint64.

        Built once from the cached formula column and stored beside the cache
        (bound to the cache hash) when the directory is writable. A formula that
        cannot be parsed gets all bits set, so it is excluded whenever an
        element filter is active.
        """

        if self._element_masks is not None:
            return self._element_masks
        cache_sha = self._metadata().get("cache_sha256", "unknown")
        sidecar = self.cache_path.with_name(f"{self.cache_path.name}.elements6-{cache_sha[:16]}.npy")
        if sidecar.is_file():
            try:
                masks = np.load(sidecar, allow_pickle=False)
                if masks.shape == (self._phase_count, 3) and masks.dtype == np.uint64:
                    self._element_masks = masks
                    return masks
            except (OSError, ValueError):
                pass
        masks = np.full((self._phase_count, 3), np.iinfo(np.uint64).max, dtype=np.uint64)
        for phase_no, formula in self._connection.execute("SELECT phase_no, formula FROM phases"):
            index = int(phase_no)
            if not 0 <= index < self._phase_count:
                continue
            parsed = parse_formula(str(formula or ""))
            if not parsed:
                continue
            low = high = 0
            for symbol in parsed:
                bit = ELEMENT_INDEX[symbol]
                if bit < 64:
                    low |= 1 << bit
                else:
                    high |= 1 << (bit - 64)
            masks[index, 0] = low
            masks[index, 1] = high
            carbon_allotrope = set(parsed) == {"C"} and parsed["C"] > 1.0 + 1e-9
            masks[index, 2] = 1 if is_molecular_organic(parsed) or carbon_allotrope else 0
        self._element_masks = masks
        try:
            temporary = sidecar.with_suffix(".tmp.npy")
            np.save(temporary, masks, allow_pickle=False)
            os.replace(temporary, sidecar)
        except OSError:
            pass
        return masks

    def element_eligibility(self, allowed_elements: Iterable[str] | None) -> np.ndarray | None:
        """Boolean array: phase contains only allowed elements (``None`` = no filter)."""

        if allowed_elements is None:
            return None
        low = high = 0
        for symbol in allowed_elements:
            bit = ELEMENT_INDEX[symbol]
            if bit < 64:
                low |= 1 << bit
            else:
                high |= 1 << (bit - 64)
        masks = self._element_mask_array()
        forbidden_low = np.uint64(~low & 0xFFFFFFFFFFFFFFFF)
        forbidden_high = np.uint64(~high & 0xFFFFFFFFFFFFFFFF)
        atmospheric = 0
        for symbol in ("H", "C", "N", "O"):
            atmospheric |= 1 << ELEMENT_INDEX[symbol]
        carbon_only = np.uint64(1 << ELEMENT_INDEX["C"])
        # Same rule as ``passes_element_filter``: at least one non-atmospheric
        # element (all non-atmospheric bits of ``low``/``high`` count), or
        # elemental carbon.
        not_atmospheric_low = np.uint64(~atmospheric & 0xFFFFFFFFFFFFFFFF)
        has_other = ((masks[:, 0] & not_atmospheric_low) != 0) | (masks[:, 1] != 0)
        is_carbon = (masks[:, 0] == carbon_only) & (masks[:, 1] == 0)
        return (
            ((masks[:, 0] & forbidden_low) == 0)
            & ((masks[:, 1] & forbidden_high) == 0)
            & (masks[:, 2] == 0)
            & (has_other | is_carbon)
        )

    def _phase_from_row(
        self,
        row: sqlite3.Row,
        radiation: Radiation,
        d_ranges: Iterable[tuple[float, float]] | None = None,
    ) -> ReferencePhase | None:
        cache_key = (int(row["phase_no"]), float(radiation.wavelength_angstrom))
        cached = self._decoded_phase_cache.get(cache_key)
        if cached is not None:
            self._decoded_phase_cache.move_to_end(cache_key)
            d_values, phase = cached
        else:
            d_values, phase = self._decode_phase(row, radiation)
            self._decoded_phase_cache[cache_key] = (d_values, phase)
            if len(self._decoded_phase_cache) > POWCOD_DECODED_PHASE_CACHE_SIZE:
                self._decoded_phase_cache.popitem(last=False)
        if d_ranges is not None:
            ranges = np.asarray(tuple(d_ranges), dtype=float).reshape(-1, 2)
            if ranges.size == 0 or not bool(
                np.any((d_values[:, None] >= ranges[None, :, 0]) & (d_values[:, None] <= ranges[None, :, 1]))
            ):
                return None
        return phase

    def _decode_phase(
        self,
        row: sqlite3.Row,
        radiation: Radiation,
    ) -> tuple[np.ndarray, ReferencePhase | None]:
        """Decode one cached row (pure for a fixed store and wavelength)."""

        d_values, intensities, hkl_values = _decode_reflection_arrays(row["reflection_blob"])
        # Vectorized Bragg filter to the 0-120 degree window.
        argument = radiation.wavelength_angstrom / (2.0 * np.maximum(d_values, 1e-12))
        valid = (d_values > 0) & (argument <= 1.0)
        angles = np.full(d_values.shape, np.inf)
        angles[valid] = np.degrees(2.0 * np.arcsin(argument[valid]))
        keep = np.flatnonzero((angles >= 0.0) & (angles <= 120.0))
        if keep.size == 0:
            return d_values, None
        if keep.size > POWCOD_MAX_LINES_PER_PHASE:
            # Very large cells list thousands of weak reflections; keep the
            # strongest ones (in database order) to bound decoding cost.
            strongest = np.argsort(-intensities[keep], kind="stable")[:POWCOD_MAX_LINES_PER_PHASE]
            keep = np.sort(keep[strongest])
        lines = [
            ReferenceLine(float(d_values[index]), float(intensities[index]), hkl_values[index] if hkl_values is not None else None)
            for index in keep
        ]
        equivalence = self._equivalence.lookup(str(row["reference_id"])) if self._equivalence else None
        return d_values, ReferencePhase(
            reference_id=str(row["reference_id"]),
            formula=str(row["formula"]),
            name=equivalence.preferred_name if equivalence else str(row["name"]),
            space_group=str(row["space_group"]),
            lines=tuple(lines),
            source="pow_cod",
            cod_entry_url=str(row["source_url"]),
            cod_entry_id=str(row["cod_id"]),
            equivalence_group_id=equivalence.group_id if equivalence else None,
            parent_family_group_id=equivalence.parent_family_group_id if equivalence else None,
            equivalence_kind=equivalence.equivalence_kind if equivalence else None,
            equivalence_confidence=equivalence.confidence if equivalence else None,
        )

    def _rows_by_reference_ids(self, reference_ids: Iterable[str]) -> tuple[sqlite3.Row, ...]:
        unique = tuple(sorted(set(reference_ids)))
        rows: list[sqlite3.Row] = []
        for offset in range(0, len(unique), 900):
            chunk = unique[offset : offset + 900]
            placeholders = ",".join("?" for _ in chunk)
            rows.extend(
                self._connection.execute(
                    f"SELECT * FROM phases WHERE reference_id IN ({placeholders}) ORDER BY phase_no", chunk
                ).fetchall()
            )
        return tuple(rows)

    def _rows_by_phase_numbers(self, phase_numbers: Iterable[int]) -> tuple[sqlite3.Row, ...]:
        unique = tuple(sorted({int(value) for value in phase_numbers if int(value) >= 0}))
        rows: list[sqlite3.Row] = []
        for offset in range(0, len(unique), 900):
            chunk = unique[offset : offset + 900]
            placeholders = ",".join("?" for _ in chunk)
            rows.extend(
                self._connection.execute(
                    f"SELECT * FROM phases WHERE phase_no IN ({placeholders}) ORDER BY phase_no", chunk
                ).fetchall()
            )
        return tuple(rows)

    def _phase_rows(
        self,
        reference_ids: Iterable[str],
        radiation: Radiation,
        d_ranges: Iterable[tuple[float, float]] | None = None,
    ) -> tuple[ReferencePhase, ...]:
        phases = [self._phase_from_row(row, radiation, d_ranges) for row in self._rows_by_reference_ids(reference_ids)]
        return tuple(phase for phase in phases if phase is not None)

    def get(self, reference_id: str, radiation: Radiation | str = "Cu Ka") -> ReferencePhase:
        normalized = reference_id if reference_id.startswith("powcod:") else f"powcod:{reference_id}"
        phases = self._phase_rows((normalized,), get_radiation(radiation))
        if not phases:
            raise KeyError(reference_id)
        return phases[0]

    def all(self, radiation: Radiation | str = "Cu Ka") -> tuple[ReferencePhase, ...]:
        ids = (str(row[0]) for row in self._connection.execute("SELECT reference_id FROM phases ORDER BY reference_id"))
        return self._phase_rows(ids, get_radiation(radiation))

    def _candidate_phase_bitsets(self, ranges: Iterable[tuple[float, float]]) -> tuple[int, ...]:
        """Return one packed phase bitset per observed d-spacing range.

        The previous implementation merged every matching bin into a Python
        ``bytearray`` and then materialized every phase number.  For a full
        POW_COD release, ordinary scans can match almost the entire universe;
        that made the later matcher decode hundreds of thousands of phase
        blobs before applying its small result limit.  Keeping each range as a
        Python integer lets the bitwise work run in C and enables a bounded,
        deterministic ranking before any reflection blobs are decoded.
        """

        bitsets: list[int] = []
        for lower, upper in ranges:
            first = max(0, int(math.floor(lower / self._d_bin_width)))
            last = max(first, int(math.floor(upper / self._d_bin_width)))
            bins: list[int] = []
            if first >= POWCOD_HIGH_D_BIN or last >= POWCOD_HIGH_D_BIN:
                bins.append(POWCOD_HIGH_D_BIN)
                last = POWCOD_HIGH_D_BIN - 1
            if first <= last:
                bins.extend(range(first, last + 1))
            if not bins:
                bitsets.append(0)
                continue
            mask = 0
            ordered_bins = tuple(sorted(set(bins)))
            for offset in range(0, len(ordered_bins), 900):
                chunk = ordered_bins[offset : offset + 900]
                placeholders = ",".join("?" for _ in chunk)
                for row in self._connection.execute(
                    f"SELECT phase_bits FROM d_bin_index WHERE bin IN ({placeholders})", chunk
                ):
                    mask |= int.from_bytes(bytes(row[0]), "little", signed=False)
            bitsets.append(mask)
        return tuple(bitsets)


    def _bounded_candidate_order(
        self,
        range_weights: tuple[float, ...],
        bitsets: tuple[int, ...],
        *,
        priority_budget: int,
        eligible: np.ndarray | None = None,
    ) -> tuple[int, ...]:
        """Return every coarse hit in the bounded policy's deterministic order.

        The first ``priority_budget`` values preserve the established
        compactness/major-support lanes. Remaining values are ordered by those
        same lanes and are available for exact-filter backfill.
        """

        merged = 0
        for bitset in bitsets:
            merged |= bitset
        candidate_count = merged.bit_count()
        if candidate_count == 0:
            return ()
        if candidate_count <= priority_budget:
            numbers = self._candidate_phase_numbers_from_bitset(merged)
            if eligible is not None:
                numbers = tuple(number for number in numbers if number < eligible.size and eligible[number])
            return numbers
        byte_count = max(1, (self._phase_count + 7) // 8)
        intensities = np.asarray(range_weights, dtype=np.float64)
        maximum = float(np.max(intensities)) if intensities.size else 0.0
        weights = intensities / maximum if maximum > 0.0 else np.ones(len(bitsets), dtype=np.float64)
        # Restrict the per-phase counting to eligible phases when an element
        # filter is active (a few hundred instead of ~490k).
        universe = np.flatnonzero(eligible) if eligible is not None else None
        size = universe.size if universe is not None else self._phase_count
        hit_count = np.zeros(size, dtype=np.uint16)
        weighted_hits = np.zeros(size, dtype=np.float64)
        for weight, bitset in zip(weights, bitsets, strict=True):
            bits = np.unpackbits(
                np.frombuffer(bitset.to_bytes(byte_count, "little", signed=False), dtype=np.uint8),
                bitorder="little",
            )[: self._phase_count]
            if universe is not None:
                bits = bits[universe]
            hit_count += bits
            weighted_hits += bits * float(weight)
        local = np.flatnonzero(hit_count)
        candidates = universe[local] if universe is not None else local
        candidate_hits = hit_count[local]
        candidate_weighted = weighted_hits[local]
        if candidates.size == 0:
            return ()
        # The bounded query reserves most of its budget for compact, coherent
        # line evidence while keeping a smaller major-peak-support lane. This
        # prevents a large, dense reference from winning only because it has
        # many opportunities for coarse-bin coincidence, without returning to
        # compactness-only lookup that can miss a phase explaining dominant
        # measured peaks. The count vector is loaded once per read-only store.
        compactness = candidate_hits / np.maximum(self._reflection_count_array()[candidates], 1.0)
        support_order = np.lexsort(
            (candidates, -compactness, -candidate_hits, -candidate_weighted)
        )
        compactness_order = np.lexsort(
            (candidates, -candidate_weighted, -candidate_hits, -compactness)
        )
        compactness_quota, major_support_quota = _bounded_retrieval_quotas(priority_budget)
        selected: list[int] = []
        selected_set: set[int] = set()
        for order, quota in (
            (compactness_order, compactness_quota),
            (support_order, major_support_quota),
        ):
            for candidate_index in order[:quota]:
                phase_number = int(candidates[candidate_index])
                if phase_number not in selected_set:
                    selected.append(phase_number)
                    selected_set.add(phase_number)
        # Remaining coarse hits (exact-filter backfill order): compactness order
        # first, then support order, skipping numbers already selected. This is
        # the same order as the previous per-element loop, computed in numpy.
        tail = np.concatenate([candidates[compactness_order], candidates[support_order]])
        if selected:
            tail = tail[~np.isin(tail, np.asarray(selected, dtype=tail.dtype))]
        _, first_positions = np.unique(tail, return_index=True)
        tail = tail[np.sort(first_positions)]
        return tuple(selected) + tuple(int(value) for value in tail)

    def _exact_candidate_backfill(
        self,
        phase_numbers: tuple[int, ...],
        radiation: Radiation,
        ranges: tuple[tuple[float, float], ...],
        *,
        limit: int,
    ) -> tuple[tuple[ReferencePhase, ...], dict[str, int | bool]]:
        """Verify coarse hits against exact d ranges before filling the pool.

        POW_COD's compact bitset bins are deliberately wider than a peak
        tolerance. A coarse false positive must not consume a fitter slot if a
        later-ranked candidate has an exact reflection in range. This scans
        deterministic batches and stops once the requested exact pool is full;
        the diagnostics distinguish a complete scan from an early bounded
        stop so callers can retain the remaining truncation uncertainty.
        """

        accepted: list[ReferencePhase] = []
        rejected = 0
        scanned = 0
        for offset in range(0, len(phase_numbers), 900):
            batch = phase_numbers[offset : offset + 900]
            rows = self._rows_by_phase_numbers(batch)
            by_number = {int(row["phase_no"]): row for row in rows}
            for phase_number in batch:
                row = by_number.get(phase_number)
                if row is None:
                    continue
                scanned += 1
                phase = self._phase_from_row(row, radiation, ranges)
                if phase is None:
                    rejected += 1
                    continue
                accepted.append(phase)
                if len(accepted) >= limit:
                    return tuple(accepted), {
                        "scanned_coarse_candidate_count": scanned,
                        "exact_prefilter_rejected_count": rejected,
                        "exact_candidates_found_in_scan": len(accepted),
                        "retrieval_complete": scanned == len(phase_numbers),
                        "backfilled_after_exact_filter": rejected > 0,
                    }
        return tuple(accepted), {
            "scanned_coarse_candidate_count": scanned,
            "exact_prefilter_rejected_count": rejected,
            "exact_candidates_found_in_scan": len(accepted),
            "retrieval_complete": True,
            "backfilled_after_exact_filter": rejected > 0,
        }

    def _exhaustive_exact_candidate_numbers(
        self,
        range_weights: tuple[float, ...],
        ranges: tuple[tuple[float, float], ...],
        max_candidates: int,
        eligible: np.ndarray | None = None,
    ) -> tuple[tuple[int, ...], int, int]:
        """Scan every cached phase and rank only exact line-position hits.

        This is deliberately an opt-in evaluation path.  It avoids the coarse
        d-bin false-negative risk by decoding each phase's compressed
        reflection evidence, then orders exact hits by measured-intensity
        support, hit count, and reference ID, matching the major-peak-first
        objective of bounded retrieval. The caller still receives a bounded
        pool, so reports must retain the exact candidate count and truncation
        flag when the pool is smaller than the match set.
        """

        ranked: list[tuple[int, int, float]] = []
        scanned = 0
        intensities = np.asarray(range_weights, dtype=np.float64)
        maximum = float(np.max(intensities)) if intensities.size else 0.0
        weights = intensities / maximum if maximum > 0.0 else np.ones(len(ranges), dtype=np.float64)
        for row in self._connection.execute(
            "SELECT phase_no, reflection_blob FROM phases ORDER BY phase_no"
        ):
            scanned += 1
            if eligible is not None and not eligible[int(row["phase_no"])]:
                continue
            d_spacings = _decode_d_spacings(row["reflection_blob"])
            hit_count = 0
            weighted_hits = 0.0
            for weight, (lower, upper) in zip(weights, ranges, strict=True):
                if bool(np.any((d_spacings >= lower) & (d_spacings <= upper))):
                    hit_count += 1
                    weighted_hits += float(weight)
            if hit_count:
                ranked.append((int(row["phase_no"]), hit_count, weighted_hits))
        ranked.sort(key=lambda value: (-value[2], -value[1], value[0]))
        return tuple(value[0] for value in ranked[:max_candidates]), len(ranked), scanned

    @staticmethod
    def _candidate_phase_numbers_from_bitset(bitset: int) -> tuple[int, ...]:
        numbers: list[int] = []
        remaining = bitset
        while remaining:
            lowest = remaining & -remaining
            numbers.append(lowest.bit_length() - 1)
            remaining ^= lowest
        return tuple(numbers)

    def iter_candidates(
        self,
        peaks: Iterable[Peak],
        radiation: Radiation | str,
        tolerance_deg: float,
        *,
        max_candidates: int | None = None,
        retrieval_mode: str = "bounded_coarse",
        allowed_elements: Iterable[str] | None = None,
        d_relative_tolerance: float = 0.0,
    ) -> tuple[ReferencePhase, ...]:
        selected = get_radiation(radiation)
        if not math.isfinite(d_relative_tolerance) or not 0.0 <= d_relative_tolerance <= 0.05:
            raise ValueError("d_relative_tolerance must be between 0 and 0.05")
        eligible = self.element_eligibility(tuple(allowed_elements) if allowed_elements is not None else None)
        if not math.isfinite(tolerance_deg) or tolerance_deg <= 0:
            raise ValueError("tolerance_deg must be positive and finite")
        if max_candidates is None:
            max_candidates = POWCOD_DEFAULT_CANDIDATE_LIMIT
        if isinstance(max_candidates, bool) or not isinstance(max_candidates, int) or max_candidates <= 0:
            raise ValueError("max_candidates must be a positive integer")
        if retrieval_mode not in POWCOD_RETRIEVAL_MODES:
            raise ValueError(f"retrieval_mode must be one of {POWCOD_RETRIEVAL_MODES}")
        observed_peaks = tuple(peaks)
        ranges: list[tuple[float, float]] = []
        range_weights: list[float] = []
        for peak in observed_peaks:
            lower = max(1e-9, float(peak.position_deg) - tolerance_deg)
            upper = min(179.999999, float(peak.position_deg) + tolerance_deg)
            if lower >= upper:
                continue
            try:
                values = (d_from_two_theta(lower, selected), d_from_two_theta(upper, selected))
            except ValueError:
                continue
            # Widen by the relative lattice tolerance so phases whose cell differs
            # slightly from the database entry are still retrieved.
            ranges.append((min(values) * (1.0 - d_relative_tolerance), max(values) * (1.0 + d_relative_tolerance)))
            range_weights.append(max(float(peak.intensity), 0.0))
        if not ranges:
            self._last_query_stats = {
                "candidate_limit": max_candidates,
                "candidate_count": 0,
                "returned_count": 0,
                "truncated": False,
                "retrieval_mode": retrieval_mode,
                "scanned_phase_count": 0,
                "selection": (
                    "exhaustive_exact_line_hits"
                    if retrieval_mode == "exhaustive_exact"
                    else "compactness_major_support_union_coarse_d_bin_hits"
                ),
                "retrieval_policy_version": POWCOD_RETRIEVAL_POLICY_VERSION,
                "compactness_quota": 0,
                "major_support_quota": 0,
            }
            return ()
        range_tuple = tuple(ranges)
        if retrieval_mode == "exhaustive_exact":
            phase_numbers, candidate_count, scanned_phase_count = self._exhaustive_exact_candidate_numbers(
                tuple(range_weights), range_tuple, max_candidates, eligible
            )
            selection = "exhaustive_exact_line_hits"
            phases = [
                self._phase_from_row(row, selected, ranges)
                for row in self._rows_by_phase_numbers(phase_numbers)
            ]
            result = tuple(phase for phase in phases if phase is not None)
            exact_stats: dict[str, int | bool] = {
                "coarse_candidate_count": candidate_count,
                "scanned_coarse_candidate_count": scanned_phase_count,
                "exact_prefilter_rejected_count": 0,
                "exact_candidates_found_in_scan": len(result),
                "retrieval_complete": True,
                "backfilled_after_exact_filter": False,
            }
        else:
            bitsets = self._candidate_phase_bitsets(range_tuple)
            merged = 0
            for bitset in bitsets:
                merged |= bitset
            candidate_count = merged.bit_count()
            phase_numbers = self._bounded_candidate_order(
                tuple(range_weights), bitsets, priority_budget=max_candidates, eligible=eligible
            )
            if eligible is not None:
                candidate_count = len(phase_numbers)
            selection = "compactness_major_support_union_coarse_d_bin_hits"
            result, exact_stats = self._exact_candidate_backfill(
                phase_numbers,
                selected,
                range_tuple,
                limit=max_candidates,
            )
            exact_stats = {"coarse_candidate_count": candidate_count, **exact_stats}
            scanned_phase_count = int(exact_stats["scanned_coarse_candidate_count"])
        compactness_quota, major_support_quota = (
            _bounded_retrieval_quotas(max_candidates)
            if retrieval_mode == "bounded_coarse" and candidate_count > max_candidates
            else (0, 0)
        )
        self._last_query_stats = {
            "candidate_limit": max_candidates,
            "candidate_count": candidate_count,
            "returned_count": len(result),
            "truncated": (
                candidate_count > max_candidates
                if retrieval_mode == "exhaustive_exact"
                else not bool(exact_stats["retrieval_complete"])
            ),
            "retrieval_mode": retrieval_mode,
            "scanned_phase_count": scanned_phase_count,
            "selection": selection,
            "retrieval_policy_version": POWCOD_RETRIEVAL_POLICY_VERSION,
            "compactness_quota": compactness_quota,
            "major_support_quota": major_support_quota,
            "element_filter": (
                {"allowed_elements": sorted(allowed_elements), "eligible_phase_count": int(eligible.sum())}
                if eligible is not None and allowed_elements is not None
                else None
            ),
            **exact_stats,
        }
        return result

    def __iter__(self) -> Iterable[ReferencePhase]:
        return iter(self.all())

    def close(self) -> None:
        connection = getattr(self, "_connection", None)
        if connection is not None:
            connection.close()
            self._connection = None
        if self._equivalence is not None:
            self._equivalence.close()
            self._equivalence = None

    def __enter__(self) -> "PowCodReferenceStore":
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:
            pass


__all__ = [
    "POWCOD_ADAPTER_VERSION",
    "POWCOD_D_BIN_WIDTH_ANGSTROM",
    "POWCOD_HIGH_D_BIN",
    "POWCOD_INDEX_KIND",
    "POWCOD_DEFAULT_CANDIDATE_LIMIT",
    "POWCOD_RETRIEVAL_MODES",
    "POWCOD_MAX_INDEX_D_ANGSTROM",
    "POWCOD_RETRIEVAL_POLICY_VERSION",
    "POWCOD_RELEASE",
    "POWCOD_SCHEMA_VERSION",
    "POWCOD_SOURCE_URL",
    "PowCodCacheResult",
    "PowCodError",
    "PowCodReferenceStore",
    "build_powcod_cache",
    "verify_powcod_source",
    "write_powcod_manifest",
]
